### ISSUE TITLE
Question: What is the reason for read1 and read2 having different range_start range_stop coordinates in the GEM_Mapper tutorial?

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/tadbit#110]
I guess the question itself is pretty self-explanatory. So can you please elaborate why it contains two different ranges for read1 and read2?

 is there some kind of computation that it's doing seeing some kind of insert size?

 or is it just to let people know that different ranges can be used? 

On hindsight would you use different ranges for mate pairs and if so why?

**Comment by fransua** [comment]
Hi @kipal1988,
because in the example of the tutorial (files from dixon2012), read1 and read2 belong from a single fastq file where they are just on a single read, one after the other. This is also confirmed by the the shape of the PHRED quality score along the sequence where you can clearly see the repeated pattern of raise and fall of qualiy pointing that we are dealing with 2 reads, one after tehe other.
And usually, yes, you will have one read per file and will use the same start/end ranges in both cases.
