### ISSUE TITLE
Question regarding read count in SAM file produced by GEM_Mapper

### ISSUE THREAD

**Issue by kipal1988** [3DGenomes/tadbit#111]
Hi fransua,

I know that I should just ask the developer about this, but since you guys also use this class function I was wondering if you've seen this in GEM_Mapper's sam output. For example, when I am mapping 1 million reads, and I grep out the XT:A:U feature for unique maps, XT:A:R for multi-maps. I find that 19k have mapped uniquely.
Furthermore, multi-maps number around 36k. But if I look at the unmapped, it's around 300k.

therefore 19000 + 36000 + 300000 does not come out to 1 million. 

But in many files all reads are reported. This is after using awk's array method to find the total number of reads present in the file.

Have you noticed this in your data as well? Do you know why it reports only a few, while others are never reported at all? 

because I think either they are unmapped or mapped or multi-mapped (including random positions taking into consideration the MAPQ values).

**Comment by fransua** [comment]
Hi @kipal1988 ,
first I am really not an expert in SAM format, I use the strict minimum needed to get the uniquely mapped reads, and was told by the GEM guys which filed I should look at in order to get it right.
This said, :)
I don't think that XT:A:U stands for uniquely mapped reads, what I do in tadbit is to search for NH:i:1(https://github.com/3DGenomes/tadbit/blob/master/_pytadbit/mapping/mapper.py#L410).

for the second part of the question, about the loss of reads, no I haven't noticed it. At least in the first iteration of the mapping, further iterations are done on reduced sets of reads.

*I am currently implementing a new version of the iterative mapping, that will use directly the .map format used by GEM, and hopefully things will be more easy to understand.*

thanks for the feedback
