### ISSUE TITLE
Fix matrix visualization of normalized experiments

### ISSUE THREAD

**Issue by fransua** [3DGenomes/TADbit#116]

**Comment by Biojenifer** [comment]
Hi!

I am following TADbit tutorial, but after normalize a matrix I cannot visualize it in some chromosomes (for example: chromosome 3) because matplotlib called by hic_map reports the following error: 

raise ValueError("data mapping points must have x in increasing order")

My command line is the same for every chromosome:

hic_data.normalize_hic(iterations=100, max_dev=0.00001

hic_map(hic_data, normalized=True, focus = '3', show=True, cmap='tadbit', savefig= 'pathtooutfile')

Could you please give me some advice on how to solve this issue? 
Thanks in advance.
