### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#150]
Hi,

I have a question regarding the normalization step. I know I can normalize matrices genome vs genome or chrA vs chrA (squared matrices). But, can I normalize non-squared matrices such as chrA vs chrB?

Thank you.

**Comment by fransua** [comment]
Hi @apaytuvi 
not sure to understand your point. The normalization is done over a single matrix and consists basically in dividing each cell by the product of its row with its column. The output is a matrix where the sum of all  rows will tend to be the same.

**Comment by apaytuvi** [comment]
Thanks for your reply, @fransua 

Indeed the normalization works that way, dividing each cell by the product of its row with its column. When normalizing a matrix storing the counts for the whole genome, let's say 500x500, only a few colums will have a low count number or count = 0. These columns are masked. The same happens when normalizing a matrix for the intrachromosomal contacts of e.g. chr1.

However, in matrices storing interchromosomal contacts, let's say chr4 vs chr3, 200x150, I would expect quite a lot of columns having a low count number or 0 counts. Isn't that a problem?

How sparse must be a matrix to prevent its normalization?

**Comment by fransua** [comment]
Ok, 
Perhaps you could have a look to supplementary figure 15 of the ICE paper (http://www.nature.com/nmeth/journal/v9/n10/full/nmeth.2148.html). According to it the variance starts to be very high if the number of counts in your matrix is bellow 2500 (for the human genome).
Also I would recommend you to normalize the full genomic matrix instead of doing it by chromsome (or iter-chromosomal space), otherwise you are going to introduce a new bias which is the matrix size.
