### ISSUE TITLE
A/B compartment visualization using Experiment class

### ISSUE THREAD

**Issue by rnakato** [3DGenomes/TADbit#195]
Hi,
I'd like to visualize the contact map with the A/B compartment information using my own contact map data, as shown in https://3dgenomes.github.io/TADbit/tutorial/tutorial_0_mapping.html#filtering-and-normalization.
I think it is possible to generate compartment information from a contact map itself, but Experiment class does not have a function to analyze compartments.
Is it possible to visualize A/B compartment using Experiment class?

**Comment by fransua** [comment]
Hi,
for now the compartment analysis is outside the Experiment class. The main reason for this is because the normalization should be done on full genomes.
However I think that the view you are asking can be generated setting the parameter show to True, or savefig to some path in the [find_compartments](https://3dgenomes.github.io/TADbit/reference/reference_hic_data.html#pytadbit.parsers.hic_parser.HiC_data.find_compartments) function

**Comment by rnakato** [comment]
Dear fransua,
Thank you, I will try.
