### ISSUE TITLE
Get matrix from `hic_map` with head lines

### ISSUE THREAD

**Issue by Tong-Chen** [3DGenomes/tadbit#99]
Dear Francois,

I wonder if there is any way to let function `hic_map` output matrix with head lines when `savedata=specificied_path`.

I have added the following code to generate headline. Please check if it is OK? I think you must have a better way to do it.

```
                if savedata:
                    out = open('%s/%s.mat' % (
                        savedata, '_'.join(set((crm1, crm2)))), 'w')
		    #----Add 0329 by CT---------
		    hLen = len(subdata[0]) + 1
		    headLine = '\t'.join([crm1+"_"+str(num) for num in range(1,hLen)])
		    out.write(headLine + '\n')
		    start_94 = 1
		    for d in subdata:
			label = '_'.join([crm2, str(start_94)])
			valueL = '\t'.join([str(i) for i in d])
			out.write(label + '\t' + valueL + '\n')
			start_94 += 1
		    #----Add 0329 by CT---------
                    #out.write('\n'.join(['\t'.join([str(i) for i in d])
                    #                     for d in subdata]) + '\n')
                    out.close()
```

Thanks!

Chen Tong

**Comment by fransua** [comment]
Hi Chen Tong,
this is a very good remark. I think it is fixed in this very last commit. At least partly, as I preferred for now use row-names instead of column names. Like this I can use one column for chromosome names and one column for genomic coordinates. It is also a bit easier to parse and use once written.
I hope this solves your issue.

thanks!
